### ISSUE TITLE
Librairie Javascript de chiffrement

### ISSUE THREAD

**Issue by ViBiOh** [Hakujou/PasswordManager#1]
https://github.com/openpgpjs/openpgpjs

Ce dont je vous parlais mardi, une librairie Javascript afin de chiffrer des données côté navigateur.

[Ainsi qu'une petite description sur ProtonMail](https://protonmail.com/security-details)

L'idéal est de chiffrer avec un mot de passe que vous ne stockez pas i.e. dont seul l'utilisateur à le secret.

Votre base de données est donc sûre car chiffrée, toutes les informations transitent chiffrées et ce n'est que sur le navigateur, avec le bon mot de passe (qui n'est jamais stocké/transmis), que l'on déchiffre le contenu.

**Comment by loicmarne** [comment]
Merci beaucoup !

**Comment by Hakujou** [comment]
Attention aussi à ne pas confondre la clé de déchiffrement locale avec le password de l'utilisateur, c'est deux choses différentes.
Le password **doit** être envoyé au BackEnd pour s'authentifier, alors que la clé de chiffrement doit rester en Front. Par contre en cas de perte c'est foutu pour l'utilisateur.

**Comment by loicmarne** [comment]
Je suis d'accord, le tout est juste d'avoir un échange de "boites noires" entre le front-end et le back-end

**Comment by Hakujou** [comment]
@loicmarne Est-ce que ça a été implémenté ? Que je sache si je peux clore l'issue ou pas.

**Comment by loicmarne** [comment]
pas intégré avec le restFactory
