### ISSUE TITLE
Correction API REST

### ISSUE THREAD

**Issue by loicmarne** [Hakujou/PasswordManager#10]
Il faut modifier l'api REST coté back et front pour la modification d'un couple, !
En effet, on à actuellement deux méthode pour la modification dans l'api ; 

- modifier identidiant d'un couple
- modifier mot de passe d'un couple

Or pour une meilleur ergonomie, on peut modifier les deux en meme tps (et du coup en un seul call), de + il est également possible de modifier le site qui concerne le couple.

Il faudrait ainsi faire les mofifs front (je m'en occupe avec ALEX) et back.

Je modifie ainsi le tableau permettant la correspondance entre le front et le back (https://docs.google.com/spreadsheets/d/1mekEhsQfBxDOJpg2v102dUYAbmj8oR6XW9Vgq7u0Wek/edit#gid=1675968423)

**Comment by Hakujou** [comment]
La méthode a bien été implémentée selon ces spécifications.
Attention toutefois, tous les attributs doivent être passés (même ceux non modifiés) sans quoi ils seront mis  à jour en null.

**Comment by loicmarne** [comment]
Ok je fais le check coté front et renverrai les mêmes données si rien n'a changé.
