### ISSUE TITLE
Remarques

### ISSUE THREAD

**Issue by ViBiOh** [Hakujou/PasswordManager#2]
Pensez à mettre vos prénoms dans le README, que je puisse m'y retrouver (pas forcément vos noms si vous avez peur des moteurs de recherches, mais le prénom est déjà bien).

Bien d'avoir mis en place jscs/jshint pour analyser la qualité de votre code Javascript. Ces deux outils sont plus ou moins obsolètes de nos jours (le monde JS évolue à toute vitesse). Si vous en avez le temps, penchez-vous sur ESlint.

Sur votre `.gitignore`, les `/` en début génère de la confusion. Les fichiers de ce type sont toujours relatifs au répertoire dans lequel ils se trouvent. Avoir ici un chemin absolu est donc bizarre. Cela dit, c'est une bonne chose d'en avoir fait un !

Pensez à faire le ménage dans les fichiers générés par YeoMan. Ils contiennent beaucoup d'information sur "où mettre votre contenu". Une fois que votre contenu est ajouté ou que vous ignorez cet emplacement, enlever le commentaire. Par exemple, le code pour le suivi Google Analytics est-il toujours pertinent ?

J'aime beaucoup app/views/main.html ! Pensez à mettre ce genre de contenu dans le rapport de votre projet ;)

Attention dans le fichier `recup.js`, il y a à la fois des espaces et des tabulations pour l'indentation. Mettez-vous d'accord ;) Idem dans le `.htaccess`. Ce n'est pas gênant pour l'exécution de l'application, mais c'est déroutant pour la maintenance.

Sur le `index.php`, essayer de garder un fichier d'entrée assez simple. Toute la configuration de routage des requêtes pourrait être mise dans un autre fichier `routes.php` pour respecter le Single Responsibility Principle.

Dans le dossier fonctions, la méthode `login` me gêne un peu, ne peut-on pas l'appeler Service ou DAO plutôt ? Cherchez toujours à isoler les sources externes (SQL, requête HTTP par exemple), dans des composants séparés. Ce sera plus facile à maintenir si vous changez de base de données par exemple.

Les tests sont initiés sur la partie Javascript (sans être trop écrits), y en aura-t-il sur la partie PHP ?

A ce jour, vous êtes le projet qui utilise au mieux Git (les autres projets sont vides ou presque vides) et je vous encourage à poursuivre ! ;)

**Comment by alexandrebrba** [comment]
Merci pour tous les conseils. On va appliquer ça le plus rapidement possible!

**Comment by Hakujou** [comment]
Difficile de simplifier d'avantage le index.php étant donné que l'app est une MicroApp Phalcon. La séparation des routes requerrait par exemple une app complète, moins performante et très lourde pour une simple API REST.

J'ai créé une classe de service complète pour la méthode login, en effet plus propre. Quant aux sources externes, elles sont en réalité séparées puisqu'elles utilisent le ModelsManager : la syntaxe du PHQL ressemble à s'y méprendre à du SQL (vu la simplicité des requêtes en question) mais il y a bien ici une couche d'abstraction entre la BDD et les appels au ModelManager.

Des tests unitaires côté BackEnd sont prévus, il nous faudra intégrer PHPUnit ce qui prendra peut-être un peu de temps.
Je travaille également à la mise en place de Sentry au sein du back pour la centralisation des logs.

**Comment by Hakujou** [comment]
Tout ce qui devait être fait l'a à priori été (à l'exception des tests PHP, qui sont prévus). Je ferme.
