### ISSUE TITLE
Organisation du dépôt

### ISSUE THREAD

**Issue by loicmarne** [Hakujou/PasswordManager#4]
Salut,

J'ai "tenté" de réorganiser le dépôt, ça marche chez moi, mais il faudrait tester que tout passe bien chez vous.

Si vous pouvez mieux le réorg. allez-y.

Bonne soirée.

**Comment by Hakujou** [comment]
C'est un peu mieux rangé avec b85e2d3.
Je close l'issue.

**Comment by Hakujou** [comment]
Je ré-ouvre, plusieurs références n'ont pas été mises à jour (le .gitignore entre autres)...

**Comment by Hakujou** [comment]
Normalement corrigé pour de bon en 2d81a14.
